#!/bin/bash

echo "Running tests..."

# run the unit tests
python -m unittest discover -s test -p "test/unit_test.py"

# run the integration tests
python -m unittest discover -s test -p "test/integration_test.py"

# exit with non-zero status if any of the tests failed
if [ $? -ne 0 ]; then
    echo "Tests failed. Aborting commit."
    exit 1
fi

echo "Tests passed. Committing changes."